force-app/main/default/objects/SF_Training_Topic__c/SF_Training_Topic__c.object-meta.xml
<CustomObject>
    <label>SF Training Topic</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>SF Training Topic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF Training Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SF_Training_Topic__c/fields/Audience__c.field-meta.xml
<CustomField>
    <fullName>Audience__c</fullName>
    <label>Audience</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SF_Training_Topic__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admin Fundamentals</fullName>
            </value>
            <value>
                <fullName>APEX</fullName>
            </value>
            <value>
                <fullName>App Exchange</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SF_Training_Topic__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <label>Instructor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SF_Training_Topic__c/fields/Topic_Name__c.field-meta.xml
<CustomField>
    <fullName>Topic_Name__c</fullName>
    <label>Topic Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrainingPlanner.cls
public with sharing class TrainingPlanner {
    public TrainingPlanner() 
    {
    @AuraEnabled(cacheable=true)
    public static List<SF_Training_Topic__c> getTrainingTopics()
    {
        return [select Id, Topic_Name__c, Category__c, Audience__c,Instructor__c,Short_Description__c from SF_Training_Topic__c WITH SECURITY_ENFORCED limit 50];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<SF_Training_Topic__c> getTopicsByCat(string strCatName)
    {
        string szCN = strCatName + '%';
        return [select Id, Topic_Name__c, Category__c, Audience__c,Instructor__c,Short_Description__c 
                from SF_Training_Topic__c where Category__c like :szCN WITH SECURITY_ENFORCED limit 50];
    }
    }
}